cc = gcc
cpp = g++
objects = BinaryTraverse.out
dependencies = BinaryTree.cpp

edit: $(objects)
	echo "done"

BinaryTraverse.out : BinaryTraverse.cpp $(dependencies)
	$(cpp) -o BinaryTraverse.out BinaryTraverse.cpp $(dependencies)

clean :
	rm $(objects)
