cc = gcc
cpp = g++
objects = DFSMaze.out
dependencies = Maze.cpp

edit: $(objects)
	echo "done"

DFSMaze.out : DFSMaze.cpp $(dependencies)
	$(cpp) -o DFSMaze.out DFSMaze.cpp $(dependencies)

clean :
	rm $(objects)
